---
- hosts: ws
  become_user: root
  ignore_errors: yes
  tasks: 
    - name: Install packages
      yum:
        state: present
        name: 
          - docker
          - lsof
          - wget
          - unzip
          - passwd
          - java-11*
    - name: Create directory
      file:
        path: /opt/qa/spg
        state: directory
        mode: '0755'
    - name: Create a file
      file:
        path: /opt/qa/spg/spg.log
        state: touch
    - name: start and enable Doemon
      systemd_service:
        name: docker
        state: started
        enabled: yes
        
        