---
- hosts: ws
  become_user: root
  gather_facts: yes
  ignore_errors: yes
  tasks:
    - name: Install packages
      yum:
        state: present
        name:
          - docker
          - wget
          - lsof
          - unzip
          - passwd
          - java-11*
          
    - name: Create directory
      file:
        path: /opt/qa/spg
        state: directory
        mode: '0755'
    - name: Create a Log File
      file:
        path: /opt/qa/spg.log
        state: touch
    - name: Start and Enable docker doemon
      systemd:
        name: docker
        state: started
        enabled: yes
        
  
  