---
- hosts: wind
  tasks:
    - name: Create a file on window server
      win_file:
        path: C:\Users\Administrator\Desktop\deploy
        state: directory
    - name: Download file online
      win_get_url: 
        dest: C:\Users\Administrator\Desktop\deploy
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz
    - name: Ensure user bob is present
      win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
          - Users
   